services:
  db:
    image: postgres:16 # Use a specific version, e.g., postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_database
    ports:
      - "5434:5432" # Map port 5432 on your host to the container
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data across container restarts

volumes:
  pgdata:
